### ISSUE TITLE
Terminal doesn't display correctly

### ISSUE THREAD

**Issue by itskaizad** [notwaldorf/tiny-care-terminal#59] opened 2017-04-24 20:36 UTC
Tiny care terminal doesn't display correctly. 
Doesn't work at any window size.

![](https://s1.postimg.org/r1581jsvz/term.png)

**Node Version**: `7.7.1`
**tiny-core-terminal version**: `1.0.8`
**Shell**: `Windows`
**Terminal Program**: `cmd`
**Operating System**: `Windows 10 Creators`

Thank you!

**Comment by notwaldorf** [comment] 2017-04-24 21:03
Closing as duplicate of #14

**Closed by notwaldorf** 2017-04-24 21:03 UTC
