### ISSUE TITLE
Started crashing today

### ISSUE THREAD

**Issue by ANPez** [notwaldorf/tiny-care-terminal#150] opened 2018-05-22 05:41 UTC
I've been using it for some time without issues, but today has started crashing because of something twitter-related.

```
TypeError: Cannot read property 'replace' of undefined
    at Box.Element.parseContent (/usr/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/widgets/element.js:364:8)
    at Box.Element.render (/usr/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/widgets/element.js:1839:8)
    at /usr/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/widgets/screen.js:738:8
    at Array.forEach (<anonymous>)
    at Screen.render (/usr/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/widgets/screen.js:735:17)
    at Box.<anonymous> (/usr/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/widgets/screen.js:1936:20)
    at Box.EventEmitter._emit (/usr/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/events.js:94:20)
    at Box.EventEmitter.emit (/usr/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/events.js:117:12)
    at Program.<anonymous> (/usr/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/widgets/screen.js:518:16)
    at emitOne (events.js:116:13)
    at Program.emit (events.js:211:7)
    at Program._bindMouse (/usr/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/program.js:834:10)
    at Program.<anonymous> (/usr/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/program.js:566:10)
    at emitOne (events.js:116:13)
    at Program.emit (events.js:211:7)
    at /usr/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/program.js:418:15
```

- **Node Version**: v8.11.2
- **tiny-core-terminal version**: 1.3.2
- **Shell**: bash
- **Terminal Program**: gnome-terminal
- **Operating System**: Ubuntu 16.04.4

Thank you!

**Comment by notwaldorf** [comment] 2018-05-22 21:46
Hmm, I'm on npm 6 and node 8ish (but < 8.11) and it looks ok 🤔.
I published a new version of tiny-care-terminal (1.4.1) which has a bunch of changes -- mind giving that a try?

**Comment by Tardog** [comment] 2018-05-23 06:59
I've got the same issue, even with tiny-care-terminal 1.4.1. :(

The stack trace looks a lot like the one above, only with slightly different line numbers (tiny-care-terminal/node_modules/blessed/lib/program.js:416:23 instead of 418:15).

**Node:** v10.1.0
**npm:** 5.6.0
**Shell:** fish
**Terminal:** gnome-terminal
**OS:** Ubuntu 18.04

**Comment by ANPez** [comment] 2018-05-23 07:05
Still having the same issue with 1.4.1

**Comment by irae** [comment] 2018-05-23 12:12
I was having the same problem. I was using tiny-care-terminal without Twitter API Keys. I never bothered to setup, even though I knew it was the better idea.

Now, I followed the steps on readme and created myself the 4 keys needed, added to my `.bashrc` and everything is working again.

I would guess this is related to latest Twitter API changes. A nice summary was put up by expert twitter app developers here: http://apps-of-a-feather.com/

**Comment by mojoaxel** [comment] 2018-05-23 21:12
I cannot reproduce this.

**Comment by Tardog** [comment] 2018-05-24 05:10
I was about to try the solution posted by @irae, but backed off when Twitter demanded I add my mobile phone number to my account before creating an app. There are too many privacy concerns.

@mojoaxel Do you need more information to reproduce the bug?

**Comment by mojoaxel** [comment] 2018-05-24 05:57
> Strangely enough, it doesn't crash for me today, either. I didn't change anything.

I suspect that it was some kind of emoji in a tweet or another tweet-specific problem. If you still encounter that problem please have a look at the tweeter accounts you subscribed to. Thx!

**Comment by Tardog** [comment] 2018-05-24 12:37
> I suspect that it was some kind of emoji in a tweet or another tweet-specific problem.

Yes, make sense. Thank you!

**Comment by notwaldorf** [comment] 2018-05-24 21:02
Closing since it got resolved!

**Closed by notwaldorf** 2018-05-24 21:02 UTC
Labels: 😱 high priority, 🚨 bug

**Comment by mojoaxel** [comment] 2018-05-24 21:35
I really would love to see the tweet that causes this problem :rage:
Keep your eyes open!
