### ISSUE TITLE
Submodules no tracking

### ISSUE THREAD

**Issue by jnreynoso** [notwaldorf/tiny-care-terminal#63] opened 2017-04-25 21:15 UTC
**Node Version**: `v6.9.1`
**tiny-core-terminal version**: ` version: '1.0.8'`
**Shell**: ` zsh`
**Terminal Program**: `rxvt-unicode`
**Operating System**: `Linux (ubuntu)`

Thank you!

**Comment by Garbee** [comment] 2017-04-25 21:18
Duplicate of #56?

**Closed** 2017-04-25 21:30 UTC

**Comment by olpeh** [comment] 2017-06-01 11:15
I disagree that this issue was a Duplicate of #56 
Seems like tiny-care-terminal does not track submodules. In my previous case it did not track a git repo that was located in a subfolder, but submodule is a different thing.

I have tried multiple paths in order to get visibility for commits in submodules but without any luck sofar. Is there a bug here?

**Comment by notwaldorf** [comment] 2017-06-01 17:20
Yeah, I don't think it's duplicate and I don't know if submodules are tracked. This is just using `git-standup` or `gitlog` under the hood (if you've set TTC_GITBOT='gitlog'). If they don't, then this won't show them either.
