### ISSUE TITLE
tiny-care-terminal crashing out after a period of time

### ISSUE THREAD

**Issue by liamjones** [notwaldorf/tiny-care-terminal#101] opened 2017-05-26 07:31 UTC
tiny-care-terminal is starting up but while left open in the background I sometimes find it crashing out with the following stack trace:

````
TypeError: Cannot read property 'text' of undefined
    at /home/liam/.nvm/versions/node/v6.10.1/lib/node_modules/tiny-care-terminal/twitterbot.js:27:30
    at /home/liam/.nvm/versions/node/v6.10.1/lib/node_modules/tiny-care-terminal/node_modules/twit/lib/twitter.js:118:13
    at onRequestComplete (/home/liam/.nvm/versions/node/v6.10.1/lib/node_modules/tiny-care-terminal/node_modules/twit/lib/twitter.js:329:5)
    at Request.<anonymous> (/home/liam/.nvm/versions/node/v6.10.1/lib/node_modules/tiny-care-terminal/node_modules/twit/lib/twitter.js:341:7)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/home/liam/.nvm/versions/node/v6.10.1/lib/node_modules/tiny-care-terminal/node_modules/request/request.js:1091:12)
    at Gunzip.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
````

- **Node Version**: 6.10.1
- **tiny-core-terminal version**: 1.2.0 (git-standup version 2.1.8)
- **Shell**: zsh 5.1.1
- **Terminal Program**: Tilix (https://github.com/gnunn1/tilix)
- **Operating System**: Linux (Ubuntu 16.04.02 LTS)

(Also, thank you for writing this app! :heart:)

**Comment by notwaldorf** [comment] 2017-05-31 18:39
Uhhhhhh I have no idea how to reproduce this, unfortunately :(
It seems that you didn't receive a tweet for one of the accounts you listed. Did you change any of the defaults?

**Comment by liamjones** [comment] 2017-05-31 20:42
Nope, all are with the default accounts. Hmm, possibly our broadband connection got interrupted? I'll see if I can come up with some way to reproduce this...

**Comment by notwaldorf** [comment] 2017-05-31 20:43
I can add a null check so that it doesn't crash out (because i wrote sloppy code lol) but uhhhh i don't know what would happen! i guess it would show nothing, which is a mild improvement over it crashing, i guess :D

**Comment by mojoaxel** [comment] 2018-03-15 10:00
I have no how this could even happen!

```js
return $(".js-tweet-text.tweet-text").map(function() {
   return $(this).text();
}).get();
```
As I see it the map function should not be called if `$(".js-tweet-text.tweet-text")` is empty.
My only explanation is a bug in the map function of this jquery version.

I'm closing for now. 
**Please reopen or comment if you encounter the problem again!!**

**Closed by mojoaxel** 2018-03-15 10:00 UTC
Labels: 🚨 bug
